/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  ctrlSidebar: [
    { type: "link", label: "← Overview", href: "/docs/getting-started" },
    { type: "html", value: '<hr style="margin: 8px 0" />' },
    { type: "autogenerated", dirName: "." },
    { type: "html", value: '<hr style="margin: 8px 0" />' },
    { type: "link", label: "Rugix Bakery", href: "/docs/bakery" },
  ],
}

module.exports = sidebars
