/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    { type: "doc", id: "getting-started" },
    { type: "doc", id: "the-rugix-project" },
    { type: "html", value: '<hr style="margin: 8px 0" />' },
    { type: "link", label: "Rugix Ctrl", href: "/docs/ctrl" },
    { type: "link", label: "Rugix Bakery", href: "/docs/bakery" },
    { type: "html", value: '<hr style="margin: 8px 0" />' },
    { type: "doc", id: "production-checklist" },
    { type: "doc", id: "upgrading-from-v0.8" },
    {
      type: "category",
      label: "Experiments",
      items: [{ type: "autogenerated", dirName: "experiments" }],
    },
    { type: "html", value: '<hr style="margin: 8px 0" />' },
    {
      type: "category",
      label: "Older Versions",
      collapsed: true,
      items: [
        { type: "link", label: "0.8", href: "/docs/0.8.14/getting-started" },
        { type: "link", label: "0.7", href: "/docs/0.7.5/getting-started" },
        { type: "link", label: "0.6", href: "/docs/0.6/getting-started" },
      ],
    },
  ],
}

module.exports = sidebars
