name: Build Website

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Website
        run: pnpm build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: silitics/actions/deploy-site@main
        with:
          domain: rugix.org
          source-dir: dist
          s3-access-key: ${{ vars.SILITICS_SITES_ACCESS_KEY }}
          s3-secret-key: ${{ secrets.SILITICS_SITES_SECRET_KEY }}
